export const LOAD_SUSHI_START = "LOAD_SUSHI_START";
export const LOAD_SUSHI_SUCCESS = "LOAD_SUSHI_SUCCESS";
export const LOAD_SUSHI_ERROR = "LOAD_SUSHI_ERROR";

export const ADD_SUSHI_START = "ADD_SUSHI_START";
export const ADD_SUSHI_SUCCESS = "ADD_SUSHI_SUCCESS";
export const ADD_SUSHI_ERROR = "ADD_SUSHI_ERROR";

export const DELETE_SUSHI_START = "DELETE  _SUSHI_START";
export const DELETE_SUSHI_SUCCESS = "DELETE_SUSHI_SUCCESS";
export const DELETE_SUSHI_ERROR = "DELETE  _SUSHI_ERROR";

export const UPDATE_SUSHI_START = "UPDATE_SUSHI_START";
export const UPDATE_SUSHI_SUCCESS = "UPDATE_SUSHI_SUCCESS";
export const UPDATE_SUSHI_ERROR = "UPDATE_SUSHI_ERROR";

export const GET_SUSHI_ID = "GET_SUSHI_ID";
export const SHOW_SUSHI_INFO = "SHOW_SUSHI_INFO";
